# path to sample table
# can make a subset if required
sample_table: "config/subset.tsv"


# This section is useful for setting up references to paths that will come up repeatedly in your workflow.

# For example, you may point to the same reference genome + annotation files (.bed, .gff, etc) for different analyses.
# Once the refgenome's fasta path is registered in this file, you can refer to it with config['reference']['fasta'].

# You can also set up parameters for analyses here, s.t. you can configure and edit all your parameters from this file instead of going to each relevant rule.

reference:
  ftp: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/018/446/385/GCF_018446385.1_Zo_v1.1/GCF_018446385.1_Zo_v1.1_genomic.fna.gz"
  fasta: "data/GCF_018446385.1_Zo_v1.1_genomic.fasta"
annotation:
  ftp: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/018/446/385/GCF_018446385.1_Zo_v1.1/GCF_018446385.1_Zo_v1.1_genomic.gtf.gz"
  gtf: "data/GCF_018446385.1_Zo_v1.1_genomic.gtf"

# fastq-dump:
#  n_reads: 100000

cutadapt:
  overlap: 5
  min_length: 30

star:
  sjdbOverhang: 100
